function [ Y ] = WH( Z,CsX )
%WH  W-H transform
%Z is a matrix which is generated by SAR1,a row means a year;
CZ=bsxfun(@times, Z,CsX);
Y=bsxfun(@minus, bsxfun(@rdivide, bsxfun(@minus, CZ/6+1,CsX.*CsX/36).^3*2,CsX),2./CsX);
Y;


